---
title: REST Website
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  blog:
    title: Blog
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    author:
    is_in_topnav:
    is_in_bottomnav:
- scope:
    path: ''
    type: blogs
  values:
    permalink: "/blog/:title/"
    layout: blog
    author:
- scope:
    path: ''
    type: events
  values:
    permalink: "/events/:title/"
    layout: events
    image:
    location:
    location_maplink:
    excerpt:
    event_date:
    post_date:
    exp_date:
    is_sticky:
- scope:
    path: ''
    type: authors
  values:
    name:
    photo:
    twitterhandle:
    facebookhandle:
    bio:
markdown: kramdown
url: iwantrest.com
github_username: jeremypbeasley
permalink: pretty
newsletter_url: http://eepurl.com/pu-_9
