---
title: REST Website
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  blog:
    title: Blog
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
markdown: kramdown
url: iwantrest.com
twitter_username: canlis
github_username: jeremypbeasley
permalink: pretty
