---
title: REST Website
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  blog:
    title: Blog
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
    author: 
    is_in_topnav: 
    is_in_bottomnav: 
- scope:
    path: ''
    type: blogs
  values:
    permalink: "/blog/:title/"
    layout: blog
    author: 
- scope:
    path: ''
    type: events
  values:
    permalink: "/events/:title/"
    layout: events
    image: 
    location: 
    location_maplink: 
    excerpt: 
    event_date: 
    post_date: 
    exp_date: 
    is_sticky: 
- scope:
    path: ''
    type: authors
  values:
    name: 
    photo: 
    twitterhandle: 
    facebookhandle: 
    bio: 
markdown: kramdown
url: iwantrest.com
github_username: jeremypbeasley
permalink: pretty
newsletter_url: https://visitor.r20.constantcontact.com/d.jsp?llr=et4yig8ab&p=oi&m=1128713191012&sit=8rzcsxylb&f=bb52e12c-2e73-4ae6-a683-bd03e40285f2
