---
title: REST Website
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
  blog:
    title: Blog
    output: true
  events:
    title: Events
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: blogs
  values:
    permalink: "/blog/:title/"
    layout: blog
    author: 
- scope:
    path: ''
    type: events
  values:
    permalink: "/events/:title/"
    layout: events
<<<<<<< HEAD
    image:
    location:
    location_maplink:
    excerpt:
    event_date:
    post_date:
    exp_date:
    is_sticky:
=======
    thumbnail: 
    location: 
    location_maplink: 
    excerpt: 
    event_date: 
    post_date: 
    exp_date: 
>>>>>>> 37c36b8bf285c0ddb244db43c5719548431a6004
- scope:
    path: ''
    type: authors
  values:
<<<<<<< HEAD
    name:
    photo:
    twitterhandle:
    facebookhandle:
    bio:
=======
    name: 
    photo: 
    twitterhandle: 
    facebookhandle: 
    bio: 
>>>>>>> 37c36b8bf285c0ddb244db43c5719548431a6004
markdown: kramdown
url: iwantrest.com
twitter_username: canlis
github_username: jeremypbeasley
permalink: pretty
